# [START cloud_sql_proxy_k8s_sa]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmall-data-init-sa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmall-data-init
  template:
    metadata:
      labels:
        app: vmall-data-init
    spec:
      serviceAccountName: vmall-db-ksa
      # [END cloud_sql_proxy_k8s_sa]
      # [START cloud_sql_proxy_k8s_secrets]
      containers:
      - name: vmall-data-init
        image: fdsxaar/vmall-data-init
        env:
        - name: VMALL_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: vmall-db-secret
              key: username
        - name: VMALL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vmall-db-secret
              key: password
        - name: VMALL_DB_NAME
          valueFrom:
            secretKeyRef:
              name: vmall-db-secret
              key: database
        - name: VMALL_DB_HOST
          valueFrom:
            secretKeyRef:
              name: vmall-db-secret
              key: mysql_host
        - name: VMALL_DB_PORT
          valueFrom:
            secretKeyRef:
              name: vmall-db-secret
              key: mysql_port 
            
        #Redis proxy ip 
        - name: VMALL_REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: vmall-db-secret
              key: redis_host
        #write opt , port is 6380 
        - name: VMALL_REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: vmall-db-secret
              key: redis_port 

      # [END cloud_sql_proxy_k8s_secrets]
      # [START cloud_sql_proxy_k8s_container]
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        env:
        - name: VMALL_DB_PORT
          valueFrom:
            secretKeyRef:
              name: vmall-db-secret
              key: mysql_port 
        - name: VMALL_DB_INSTANCE_CONNECTION_NAME
          valueFrom:
            secretKeyRef:
              name: vmall-db-secret
              key: mysql_instance_connection_name 

        command:
          - "/cloud_sql_proxy"

          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          # - "-ip_address_types=PRIVATE"

          # Replace DB_PORT with the port the proxy should listen on
          # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
        
            #- "-instances=vmall-297009:us-central1:vmall=tcp:3306"
          - "-instances=$(VMALL_DB_INSTANCE_CONNECTION_NAME)=tcp:$(VMALL_DB_PORT)"
            #- "-credential_file=/secrets/service_account.json"
          
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        volumeMounts:
        - name: vmall-db-secret-sa-volume
          mountPath: /secrets/
          readOnly: true

      volumes:
      - name: vmall-db-secret-sa-volume
        secret:
          secretName: vmall-db-secret-sa     
      # [END cloud_sql_proxy_k8s_container]
